
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RPAR_LBRACK = 11;
  public static final int STRING_LITERAL = 12;
  public static final int EOF = 0;
  public static final int PREFIX = 4;
  public static final int CONCAT = 2;
  public static final int IF = 5;
  public static final int RBRACKET = 9;
  public static final int ELSE = 6;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int IDENTIFIER = 13;
  public static final int LPAREN = 7;
  public static final int REVERSE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONCAT",
  "REVERSE",
  "PREFIX",
  "IF",
  "ELSE",
  "LPAREN",
  "RPAREN",
  "RBRACKET",
  "COMMA",
  "RPAR_LBRACK",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

